# Generated by Django 3.2.19 on 2023-05-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassSites',
        ),
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(to='app.ClassSites'),
        ),
    ]
