# Generated by Django 3.2.19 on 2023-05-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230520_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isTeacher',
            field=models.BooleanField(null=True),
        ),
    ]
