# Generated by Django 3.2.19 on 2023-06-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='classAssignedTo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='classes',
        ),
        migrations.AddField(
            model_name='classsites',
            name='students',
            field=models.ManyToManyField(related_name='classes_as_student', to='app.Profile'),
        ),
        migrations.AddField(
            model_name='classsites',
            name='teachers',
            field=models.ManyToManyField(related_name='classes_as_teacher', to='app.Profile'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
