# Generated by Django 3.2.19 on 2023-06-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_title_assignment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='classAssignedTo',
            field=models.ManyToManyField(to='app.ClassSites'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
