# Generated by Django 3.2.19 on 2023-06-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20230622_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(null=True, upload_to='messages/media'),
        ),
    ]
