# Generated by Django 3.2.19 on 2023-06-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_message_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='assignments/media'),
        ),
    ]
